/* Populating the table with addresses */

INSERT INTO ADDRESS (ADDRESS_ID, HOUSENUMBER, STREETNAME, POSTALCODE, CITY, PROVINCE)
VALUES (1, 123, 'Main St', 'N9A 4X5', 'Windsor', 'Ontario');

INSERT INTO ADDRESS (ADDRESS_ID, HOUSENUMBER, STREETNAME, POSTALCODE, CITY, PROVINCE)
VALUES (2, 456, 'Maple Ave', 'N9B 1W9', 'Windsor', 'Ontario');

INSERT INTO ADDRESS (ADDRESS_ID, HOUSENUMBER, STREETNAME, POSTALCODE, CITY, PROVINCE)
VALUES (3, 789, 'Elm St', 'N9C 1A1', 'Windsor', 'Ontario');

INSERT INTO ADDRESS (ADDRESS_ID, HOUSENUMBER, STREETNAME, POSTALCODE, CITY, PROVINCE)
VALUES (4, 321, 'Oak St', 'N9E 2C3', 'Windsor', 'Ontario');

INSERT INTO ADDRESS (ADDRESS_ID, HOUSENUMBER, STREETNAME, POSTALCODE, CITY, PROVINCE)
VALUES (5, 654, 'Pine Rd', 'N9G 1Z5', 'Windsor', 'Ontario');

INSERT INTO ADDRESS (ADDRESS_ID, HOUSENUMBER, STREETNAME, POSTALCODE, CITY, PROVINCE)
VALUES (6, 987, 'Cedar Ave', 'N9H 2L9', 'Windsor', 'Ontario');

INSERT INTO ADDRESS (ADDRESS_ID, HOUSENUMBER, STREETNAME, POSTALCODE, CITY, PROVINCE)
VALUES (7, 741, 'Spruce St', 'N9J 3X6', 'Windsor', 'Ontario');

INSERT INTO ADDRESS (ADDRESS_ID, HOUSENUMBER, STREETNAME, POSTALCODE, CITY, PROVINCE)
VALUES (8, 852, 'Birch Ave', 'N9K 1A6', 'Windsor', 'Ontario');

INSERT INTO ADDRESS (ADDRESS_ID, HOUSENUMBER, STREETNAME, POSTALCODE, CITY, PROVINCE)
VALUES (9, 369, 'Chestnut Rd', 'N9L 2T1', 'Windsor', 'Ontario');

INSERT INTO ADDRESS (ADDRESS_ID, HOUSENUMBER, STREETNAME, POSTALCODE, CITY, PROVINCE)
VALUES (10, 753, 'Cherry St', 'N9M 3V7', 'Windsor', 'Ontario');

INSERT INTO ADDRESS (ADDRESS_ID, HOUSENUMBER, STREETNAME, POSTALCODE, CITY, PROVINCE)
VALUES (11, 951, 'Willow Ave', 'N9N 1A1', 'Windsor', 'Ontario');

INSERT INTO ADDRESS (ADDRESS_ID, HOUSENUMBER, STREETNAME, POSTALCODE, CITY, PROVINCE)
VALUES (12, 864, 'Cypress St', 'N9P 2B4', 'Windsor', 'Ontario');

INSERT INTO ADDRESS (ADDRESS_ID, HOUSENUMBER, STREETNAME, POSTALCODE, CITY, PROVINCE)
VALUES (13, 258, 'Beech Rd', 'N9Q 3C7', 'Windsor', 'Ontario');

INSERT INTO ADDRESS (ADDRESS_ID, HOUSENUMBER, STREETNAME, POSTALCODE, CITY, PROVINCE)
VALUES (15, 369, 'Riverdale Ave', 'N8N 1K8', 'Tecumseh', 'Ontario');

INSERT INTO ADDRESS (ADDRESS_ID, HOUSENUMBER, STREETNAME, POSTALCODE, CITY, PROVINCE)
VALUES (16, 753, 'Lesperance Rd', 'N8N 1Y4', 'Tecumseh', 'Ontario');

INSERT INTO ADDRESS (ADDRESS_ID, HOUSENUMBER, STREETNAME, POSTALCODE, CITY, PROVINCE)
VALUES (17, 951, 'Bloomfield Rd', 'N8N 3K8', 'Tecumseh', 'Ontario');

INSERT INTO ADDRESS (ADDRESS_ID, HOUSENUMBER, STREETNAME, POSTALCODE, CITY, PROVINCE)
VALUES (18, 864, 'St. Gregory Rd', 'N8N 4M5', 'Tecumseh', 'Ontario');

INSERT INTO ADDRESS (ADDRESS_ID, HOUSENUMBER, STREETNAME, POSTALCODE, CITY, PROVINCE)
VALUES (19, 258, 'Talbot Rd E', 'N8N 3W1', 'Tecumseh', 'Ontario');

INSERT INTO ADDRESS (ADDRESS_ID, HOUSENUMBER, STREETNAME, POSTALCODE, CITY, PROVINCE)
VALUES (20, 147, 'County Rd 42', 'N8N 2M1', 'Tecumseh', 'Ontario');

INSERT INTO ADDRESS (ADDRESS_ID, HOUSENUMBER, STREETNAME, POSTALCODE, CITY, PROVINCE)
VALUES (21, 852, 'Southwind Cres', 'N8N 5A5', 'Tecumseh', 'Ontario');

INSERT INTO ADDRESS (ADDRESS_ID, HOUSENUMBER, STREETNAME, POSTALCODE, CITY, PROVINCE)
VALUES (22, 741, 'Saint Pierre St', 'N8N 1C1', 'Tecumseh', 'Ontario');

INSERT INTO ADDRESS (ADDRESS_ID, HOUSENUMBER, STREETNAME, POSTALCODE, CITY, PROVINCE)
VALUES (23, 654, 'Westchester Blvd', 'N8N 2Y2', 'Tecumseh', 'Ontario');

INSERT INTO ADDRESS (ADDRESS_ID, HOUSENUMBER, STREETNAME, POSTALCODE, CITY, PROVINCE)
VALUES (24, 321, 'Renaud Line Rd', 'N8N 5C1', 'Tecumseh', 'Ontario');

INSERT INTO ADDRESS (ADDRESS_ID, HOUSENUMBER, STREETNAME, POSTALCODE, CITY, PROVINCE)
VALUES (25, 864, 'St. Gregory Rd', 'N9J 2W8', 'Amherstburg', 'Ontario');

INSERT INTO ADDRESS (ADDRESS_ID, HOUSENUMBER, STREETNAME, POSTALCODE, CITY, PROVINCE)
VALUES (26, 258, 'Lakeshore Blvd', 'N9J 2W6', 'Amherstburg', 'Ontario');

INSERT INTO ADDRESS (ADDRESS_ID, HOUSENUMBER, STREETNAME, POSTALCODE, CITY, PROVINCE)
VALUES (27, 147, 'Queen Ave', 'N9J 2W7', 'Amherstburg', 'Ontario');

INSERT INTO ADDRESS (ADDRESS_ID, HOUSENUMBER, STREETNAME, POSTALCODE, CITY, PROVINCE)
VALUES (28, 852, 'Dalhousie Ave', 'N9J 2W1', 'Tecumseh', 'Ontario');

INSERT INTO ADDRESS (ADDRESS_ID, HOUSENUMBER, STREETNAME, POSTALCODE, CITY, PROVINCE)
VALUES (29, 10, 'Ramsey St', 'N9J 2R2', 'Amherstburg', 'Ontario');

INSERT INTO ADDRESS (ADDRESS_ID, HOUSENUMBER, STREETNAME, POSTALCODE, CITY, PROVINCE)
VALUES (30, 33, 'King St', 'N9J 2W2', 'Amherstburg', 'Ontario');

INSERT INTO ADDRESS (ADDRESS_ID, HOUSENUMBER, STREETNAME, POSTALCODE, CITY, PROVINCE)
VALUES (31, 8, 'Windermere Rd', 'N9J 2W3', 'Amherstburg', 'Ontario');


/* Populating the table with contact information for patients */

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES (1, 5195551234, 'johndoe@gmail.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES (2, 5195555678, 'janedoe@yahoo.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES (3, 5195552345, 'susanjones@hotmail.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES (4, 5195559876, 'mikebrown@gmail.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES (5, 5195556789, 'jennifersmith@gmail.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES (6, 5195553456, 'robertwilson@yahoo.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES (7, 5195558765, 'jessicawilliams@hotmail.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES (8, 5195557890, 'davidlee@gmail.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES (9, 5195554567, 'karenjohnson@yahoo.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES (10, 5195552345, 'brianmiller@hotmail.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES (11, 5195556789, 'ashleytaylor@gmail.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES (12, 5195558765, 'adamjackson@yahoo.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES (13, 5195551234, 'cynthiawright@hotmail.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES (14, 5195555678, 'matthewdavis@gmail.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES (15, 5195552345, 'sarahmoore@yahoo.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES (16, 5195559876, 'jacobmartin@hotmail.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES (17, 5195556789, 'amandajohnson@gmail.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES (18, 5195553456, 'christopherbaker@yahoo.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES (19, 5195558765, 'rachelturner@hotmail.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES (20, 5195557890, 'andrewroberts@gmail.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES (21, 5195554567, 'emilyjones@yahoo.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES (22, 5195552345, 'jaredharris@hotmail.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES (23, 5195556789, 'oliviarobinson@gmail.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES (24, 5195558765, 'nicholaswright@yahoo.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES (25, 5195556789, 'realperson@yahoo.com');

/* Populating the table with contact information for doctors and nurses*/

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES(26, 2269832355, 'drkovac@greenviewmedical.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES(27, 5195550123, 'drchen@greenviewmedical.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES(28, 2265554567, 'drgreen@greenviewmedical.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES(29, 2269832355, 'drpeterson@greenviewmedical.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES(30, 5195555678, 'drrousseau@greenviewmedical.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES(31, 2265559012, 'drphil@greenviewmedical.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES(32, 5195553456, 'drmcgibbons@greenviewmedical.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES(33, 2265557890, 'drkumar@greenviewmedical.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES(34, 5195551234, 'drmckenzie@greenviewmedical.com');

/* Populating the table with contact information for nurses*/

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (35, 5195550123, 'smith@greenviewmedical.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (36, 2265554567, 'jones@greenviewmedical.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (37, 5195557890, 'williams@greenviewmedical.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (38, 2265551234, 'brown@greenviewmedical.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (39, 5195555678, 'garcia@greenviewmedical.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (40, 2265559012, 'miller@greenviewmedical.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (41, 5195553456, 'davis@greenviewmedical.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (42, 2265557890, 'rodriguez@greenviewmedical.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (43, 5195551234, 'martinez@greenviewmedical.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (44, 2265555678, 'hernandez@greenviewmedical.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (45, 5195559012, 'lopez@greenviewmedical.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (46, 2265553456, 'gonzalez@greenviewmedical.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (47, 5195556789, 'white@greenviewmedical.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (48, 2265550123, 'lee@greenviewmedical.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (49, 5195554567, 'wilson@greenviewmedical.com');

/* Populating the table with contact information for hospitals*/

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES(50, 5199908765, 'northbranch@greenviewmedical.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES(51, 5199908744, 'southwest@greenviewmedical.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES(52, 5199908722, 'central@greenviewmedical.com');

/* Populating the table with contact information for pharmacies*/
INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES(53, 5192339670, 'info@chesterspharma.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES(54, 5198912309, 'info@shoppersdrugmart.com');

INSERT INTO CONTACT (CONTACT_ID, PHONE_NUMBER, EMAIL_ADDRESS)
VALUES(54, 5198409944, 'info@pharmaplus.com');

