USE HOSPITAL_FINAL_PROJECT;

--Creating Tables

CREATE TABLE ADDRESS
(ADDRESS_ID INT NOT NULL,
HOUSENUMBER INT NOT NULL,
STREETNAME VARCHAR(100) NOT NULL,
POSTALCODE VARCHAR(7) NOT NULL,
CITY VARCHAR(15) NOT NULL,
PROVINCE VARCHAR(15) NOT NULL,
PRIMARY KEY (ADDRESS_ID));

CREATE TABLE CONTACT
(CONTACT_ID INT NOT NULL,
PHONE_NUMBER BIGINT NOT NULL,
EMAIL_ADDRESS VARCHAR(100) NOT NULL,
PRIMARY KEY (CONTACT_ID));

CREATE TABLE LOCATION_DETAILS
(LOCATION_ID INT NOT NULL,
LOCATION_NAME VARCHAR(100) NOT NULL,
ADDRESS_ID INT NOT NULL,
CONTACT_ID INT NOT NULL,
PRIMARY KEY (LOCATION_ID),
FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID),
FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT(CONTACT_ID));

CREATE TABLE EMPLOYEE_TYPE
(EMPLOYEE_TYPE_ID INT NOT NULL,
EMPLOYEE_ROLE VARCHAR(15) NOT NULL,
PRIMARY KEY (EMPLOYEE_TYPE_ID));

CREATE TABLE SPECIALIZATION
(SPECIALIZATION_ID INT NOT NULL,
SPECIALIZATION VARCHAR(100) NOT NULL,
EMPLOYEE_TYPE_ID INT NOT NULL,
PRIMARY KEY (SPECIALIZATION_ID),
FOREIGN KEY (EMPLOYEE_TYPE_ID) REFERENCES EMPLOYEE_TYPE(EMPLOYEE_TYPE_ID));

CREATE TABLE EMPLOYEE
(EMPLOYEE_ID INT NOT NULL,
FNAME VARCHAR(15) NOT NULL,
LNAME VARCHAR(15) NOT NULL,
SALARY DECIMAL(10,2) NOT NULL,
HOURS DECIMAL(10,2) NOT NULL,
NUMPATIENT INT NOT NULL,
CONTACT_ID INT NOT NULL,
ADDRESS_ID INT NOT NULL,
EMPLOYEE_TYPE_ID INT NOT NULL,
SPECIALIZATION_ID INT NOT NULL,
WORKS_AT INT NOT NULL,
PRIMARY KEY (EMPLOYEE_ID),
FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID),
FOREIGN KEY (EMPLOYEE_TYPE_ID) REFERENCES EMPLOYEE_TYPE(EMPLOYEE_TYPE_ID),
FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT(CONTACT_ID),
FOREIGN KEY (SPECIALIZATION_ID) REFERENCES SPECIALIZATION(SPECIALIZATION_ID),
FOREIGN KEY (WORKS_AT) REFERENCES LOCATION_DETAILS(LOCATION_ID));

CREATE TABLE ILLNESS
(ILLNESS_ID INT NOT NULL,
ILLNESS_NAME VARCHAR(15) NOT NULL,
ACUTENESS INT NOT NULL,
ESTIMATED_RECOVERY_TIME INT NOT NULL,
PRIMARY KEY (ILLNESS_ID));

CREATE TABLE PATIENT
(SIN INT NOT NULL,
FNAME VARCHAR(15) NOT NULL,
LNAME VARCHAR(15) NOT NULL,
ADDRESS_ID INT NOT NULL,
CONTACT_ID INT NOT NULL,
ACCOUNT DECIMAL(10,2) NOT NULL,
PRIMARY KEY (SIN),
FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID),
FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT(CONTACT_ID));

CREATE TABLE TREATMENT
(TREATMENT_ID INT NOT NULL,
COST DECIMAL(10,2) NOT NULL,
TREATMENT_DATE DATETIME NOT NULL,
PRIMARY_DOCTOR INT NOT NULL,
ILLNESS_ID INT NOT NULL,
PATIENT_ID INT NOT NULL,
TREATMENT_LOCATION INT NOT NULL,
PRIMARY KEY (TREATMENT_ID),
FOREIGN KEY (PRIMARY_DOCTOR) REFERENCES EMPLOYEE(EMPLOYEE_ID),
FOREIGN KEY (ILLNESS_ID) REFERENCES ILLNESS(ILLNESS_ID),
FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(SIN),
FOREIGN KEY (TREATMENT_LOCATION) REFERENCES LOCATION_DETAILS(LOCATION_ID));

CREATE TABLE TREATS
(TREATMENT_ID INT NOT NULL,
EMPLOYEE_ID INT NOT NULL,
FOREIGN KEY(TREATMENT_ID) REFERENCES TREATMENT(TREATMENT_ID),
FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID));

CREATE TABLE PRESCRIPTION
(PRESCRIPTION_ID INT NOT NULL,
PRESCRIPTIONNAME VARCHAR(15) NOT NULL,
PRESCRIPTIONSTRENGTH VARCHAR(15) NOT NULL,
PRESCRIPTIONROUTE VARCHAR(15) NOT NULL,
FREQUENCY VARCHAR(15) NOT NULL,
AMOUNT VARCHAR(15) NOT NULL,
REFILLS INT NOT NULL,
TREATMENT_ID INT NOT NULL,
PRIMARY KEY (PRESCRIPTION_ID),
FOREIGN KEY (TREATMENT_ID) REFERENCES TREATMENT(TREATMENT_ID));

CREATE TABLE PHARMACY
(PHARMACY_ID INT NOT NULL,
LOCATION_INFO INT NOT NULL,
NEAREST_HOSPITAL INT NOT NULL,
PRIMARY KEY (PHARMACY_ID),
FOREIGN KEY (LOCATION_INFO) REFERENCES LOCATION_DETAILS(LOCATION_ID),
FOREIGN KEY (NEAREST_HOSPITAL) REFERENCES LOCATION_DETAILS(LOCATION_ID));

CREATE TABLE HOSPITAL
(HOSPITAL_ID INT NOT NULL,
ACCOUNT DECIMAL(10,2) NOT NULL,
HOSPITAL_SPECIALIZATION VARCHAR(15) NOT NULL,
LOCATION_ID INT NOT NULL,
PRIMARY KEY (HOSPITAL_ID),
FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION_DETAILS(LOCATION_ID));